---
- name: Launch EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: us-east-2
    image: ami-0a695f0d95cefc163
    instance_type: t2.micro
    key_name: test
    security_groups: launch-wizard-5
    subnet_id: subnet-0327c84b4858fa0ac
    #instance_count: 2
    user_data_script: |
      #!/bin/bash
      apt update
      echo '#!/usr/bin/python3' > /home/ubuntu/akki.py
      cat << 'EOF' >> /home/ubuntu/akki.py
      search_text = "PasswordAuthentication no"
      replace_text = "PasswordAuthentication yes"
      with open(r'/etc/ssh/sshd_config', 'r') as file:
          data = file.read()
      data = data.replace(search_text, replace_text)
      with open(r'/etc/ssh/sshd_config', 'w') as file:
          file.write(data)
      EOF

      python3 /home/ubuntu/akki.py
      service ssh restart
      rm -rf /home/ubuntu/akki.py
      printf 'Akki\nAkki\n' | passwd ubuntu
  tasks:
    - name: Launch EC2 instance
      ec2_instance:
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        security_groups: "{{ security_groups }}"
        image_id: "{{ image }}"
        #count: "{{ instance_count }}"
        user_data: "{{ user_data_script }}"
        wait: yes
        tags:
          Name: ready_to_access-instance
        vpc_subnet_id: "{{ subnet_id }}"
      register: ec2_instance
    - name: Show EC2 instance details
      debug:
        var: ec2_instance
