---
- name: Update Package on linux system
  hosts: all
  become: yes
  tasks:
  - name: uninstall nginx
    yum:
      name: nginx
      state: absent
  - name: Install a list of packages with a list variable
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - httpd
      - httpd-tools
