---
- name: Launch EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: us-east-2
    image: ami-0a695f0d95cefc163
    instance_type: t2.micro
    key_name: test
    security_groups: launch-wizard-5
    subnet_id: subnet-0327c84b4858fa0ac
    user_data_script: |
      #!/bin/bash
      apt update
      echo '#!/usr/bin/python3' > /home/ubuntu/akki.py
      cat << 'EOF' >> /home/ubuntu/akki.py
      search_text = "PasswordAuthentication no"
      replace_text = "PasswordAuthentication yes"
      with open(r'/etc/ssh/sshd_config', 'r') as file:
          data = file.read()
      data = data.replace(search_text, replace_text)
      with open(r'/etc/ssh/sshd_config', 'w') as file:
          file.write(data)
      EOF

      python3 /home/ubuntu/akki.py
      service ssh restart
      rm -rf /home/ubuntu/akki.py
      printf 'Akki\nAkki\n' | passwd ubuntu

  tasks:
    - name: Launch EC2 instance
      ec2_instance:
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        security_groups: "{{ security_groups }}"
        image_id: "{{ image }}"
        user_data: "{{ user_data_script }}"
        count: 2
        wait: yes
        tags:
          Name: jenkinstest
        vpc_subnet_id: "{{ subnet_id }}"
      register: ec2_instance
      tags: [jenkinstest]

    - name: Delay for 20 seconds
      pause:
        seconds: 100
      tags: [jenkinstest]

    - name: Add the EC2 instance to the webservers group in the hosts file
      lineinfile:
        path: /etc/ansible/hosts
        line: "{{ item.private_ip_address }}"
        insertafter: '# [webservers]'
      become: yes
      become_user: root
      tags: [jenkinstest]
      loop: "{{ ec2_instance.instances }}"


    - name: Execute ssh-copy-id command
      shell: sshpass -p "{{ password }}" ssh-copy-id -o StrictHostKeyChecking=no ubuntu@{{ item.private_ip_address }}
      vars:
        password: Akki
      loop: "{{ ec2_instance.instances }}"
      timeout: 120

    - name: Run Another Playbook
      command: ansible-playbook /home/ubuntu/ansible_doc/wordpress-lamp_ubuntu1804/wordpress_play/playbook.yml
